apiVersion: v2
publisher: eclipse
name: codewind-plugin
version: latest
type: VS Code extension
displayName: Codewind VS Code Extension
title: Codewind Extension for VS Code
description: Codewind Extension for Theia
icon: https://raw.githubusercontent.com/eclipse/codewind-vscode/master/dev/res/img/codewind.png
repository: http://github.com/eclipse/codewind-vscode/
category: Other
firstPublicationDate: "2019-05-30"
latestUpdateDate: "2019-08-07"
spec:
  extensions:
    #- http://download.eclipse.org/codewind/codewind-vscode/master/latest/codewind-theia.vsix
    - http://time-nix.rtp.raleigh.ibm.com/plugins/codewind/codewind-theia/latest/codewind-0.7.0.vsix
